import "./globals.css";

import Head from "./head";
import AuthProvider from "@/context/AuthContext";

export const metadata = {
  title: "Notes App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head />
      <AuthProvider>
        <body className="flex flex-col min-h-screen bg-green-800/70">
          <div id="app">{children}</div>
          <div id="portal"></div>
          
        </body>
      </AuthProvider>
    </html>
  );
}
